-- PASSO 01
CREATE TABLE "PRODUTO"(
    "ID_PRODUTO" INTEGER PRIMARY KEY,
    "DESC_PRODUTO" VARCHAR2(100),
    "VALOR_PRODUTO" NUMBER
)

-- Inserindo dados na tabela "PRODUTO" (PASS0 02)
INSERT INTO "PRODUTO" ("ID_PRODUTO", "DESC_PRODUTO", "VALOR_PRODUTO") VALUES (1, 'Produto A', 10.99);
INSERT INTO "PRODUTO" ("ID_PRODUTO", "DESC_PRODUTO", "VALOR_PRODUTO") VALUES (2, 'Produto B', 25.49);
INSERT INTO "PRODUTO" ("ID_PRODUTO", "DESC_PRODUTO", "VALOR_PRODUTO") VALUES (3, 'Produto C', 5.75);
INSERT INTO "PRODUTO" ("ID_PRODUTO", "DESC_PRODUTO", "VALOR_PRODUTO") VALUES (4, 'Produto D', 15.99);
INSERT INTO "PRODUTO" ("ID_PRODUTO", "DESC_PRODUTO", "VALOR_PRODUTO") VALUES (5, 'Produto E', 8.25);
INSERT INTO "PRODUTO" ("ID_PRODUTO", "DESC_PRODUTO", "VALOR_PRODUTO") VALUES (6, 'Produto F', 19.99);
INSERT INTO "PRODUTO" ("ID_PRODUTO", "DESC_PRODUTO", "VALOR_PRODUTO") VALUES (7, 'Produto G', 12.50);
INSERT INTO "PRODUTO" ("ID_PRODUTO", "DESC_PRODUTO", "VALOR_PRODUTO") VALUES (8, 'Produto H', 7.75);
INSERT INTO "PRODUTO" ("ID_PRODUTO", "DESC_PRODUTO", "VALOR_PRODUTO") VALUES (9, 'Produto I', 14.99);
INSERT INTO "PRODUTO" ("ID_PRODUTO", "DESC_PRODUTO", "VALOR_PRODUTO") VALUES (10, 'Produto J', 9.99);
INSERT INTO "PRODUTO" ("ID_PRODUTO", "DESC_PRODUTO", "VALOR_PRODUTO") VALUES (11, 'Produto K', 12.25);
INSERT INTO "PRODUTO" ("ID_PRODUTO", "DESC_PRODUTO", "VALOR_PRODUTO") VALUES (12, 'Produto L', 6.50);
INSERT INTO "PRODUTO" ("ID_PRODUTO", "DESC_PRODUTO", "VALOR_PRODUTO") VALUES (13, 'Produto M', 17.75);
INSERT INTO "PRODUTO" ("ID_PRODUTO", "DESC_PRODUTO", "VALOR_PRODUTO") VALUES (14, 'Produto N', 22.99);
INSERT INTO "PRODUTO" ("ID_PRODUTO", "DESC_PRODUTO", "VALOR_PRODUTO") VALUES (15, 'Produto O', 14.50);
INSERT INTO "PRODUTO" ("ID_PRODUTO", "DESC_PRODUTO", "VALOR_PRODUTO") VALUES (16, 'Produto P', 8.75);
INSERT INTO "PRODUTO" ("ID_PRODUTO", "DESC_PRODUTO", "VALOR_PRODUTO") VALUES (17, 'Produto Q', 11.99);
INSERT INTO "PRODUTO" ("ID_PRODUTO", "DESC_PRODUTO", "VALOR_PRODUTO") VALUES (18, 'Produto R', 19.25);
INSERT INTO "PRODUTO" ("ID_PRODUTO", "DESC_PRODUTO", "VALOR_PRODUTO") VALUES (19, 'Produto S', 5.99);
INSERT INTO "PRODUTO" ("ID_PRODUTO", "DESC_PRODUTO", "VALOR_PRODUTO") VALUES (20, 'Produto T', 10.00);

-- PASSO 03
SELECT * FROM "PRODUTO";

-- EXIBIR IGUAIS A 1
SELECT DESC_PRODUTO, VALOR_PRODUTO
FROM PRODUTO
WHERE ID_PRODUTO=1;

-- EXIBIR TODOS MAIORES ou IGUAIS A 1
SELECT DESC_PRODUTO, VALOR_PRODUTO
FROM PRODUTO
WHERE ID_PRODUTO>=1;

-- EXIBIR TODOS MAIORES QUE 1
SELECT DESC_PRODUTO, VALOR_PRODUTO
FROM PRODUTO
WHERE ID_PRODUTO<1;

-- EXIBIR TODOS MENORES OU IGUAIS A 1
SELECT DESC_PRODUTO, VALOR_PRODUTO
FROM PRODUTO
WHERE ID_PRODUTO<=1;

-- EXIBIR DIFERENTES DE 1
SELECT DESC_PRODUTO, VALOR_PRODUTO
FROM PRODUTO
WHERE ID_PRODUTO<>1;

-- Exibir aquele que está entre um intervalo
SELECT *
FROM PRODUTO
WHERE ID_PRODUTO>1 AND ID_PRODUTO<5;

-- EXIBIR APENAS OS PRODUTOS DE DESCRICAO A E X
SELECT *
FROM PRODUTO
WHERE DESC_PRODUTO ='Produto A' OR DESC_PRODUTO ='Produto X';

-- EXIBIR APENAS OS PRODUTOS ENTRE 1 A 5
SELECT *
FROM PRODUTO
WHERE ID_PRODUTO BETWEEN 1 AND 5;

SELECT
VALOR_PRODUTO,
ROUND (VALOR_PRODUTO, 1) AS VALOR_PRODUTO_ARR, 
MOD (VALOR_PRODUTO, 2) AS RESTO_DIVISAO,
TRUNC (VALOR_PRODUTO, 1) AS VALOR_TRUNCADO,
ABS (VALOR_PRODUTO *(-1)) AS VALOR_ABSOLUTO,
SQRT (VALOR_PRODUTO) AS RAIZ_QUADRADA
FROM PRODUTO

-- FUNÇÕES DE TEXTO

SELECT
 DESC_PRODUTO AS TEXTO_ORIGINAL,
 LOWER(DESC_PRODUTO) AS TEXTO_MIN,
 UPPER(DESC_PRODUTO) AS TEXTO_MAI,
 INITCAP(DESC_PRODUTO) AS TEXTO_MIN_MAI
FROM PRODUTO;

SELECT
 DESC_PRODUTO AS TEXTO_ORIGINAL,
 CONCAT(DESC_PRODUTO, ' Em oferta') AS CONCATENAR_1,
 CONCAT('Em oferta ', DESC_PRODUTO) AS CONCATENAR_2,
 SUBSTR(DESC_PRODUTO, 1,3) AS RECORTE_TXT,
 SUBSTR(DESC_PRODUTO, 4) AS RECORTE_TXT,
 LENGHT (DESC_PRODUTO) AS QTD_CARACTERES
FROM PRODUTO;

SELECT
 DESC_PRODUTO AS TEXTO_ORIGINAL,
 LPAD(DESC_PRODUTO, 30, '.')
FROM PRODUTO;