DROP TABLE ALUNO;

CREATE TABLE ALUNO(
    RM INTEGER,
    NOME VARCHAR(60)
);

CREATE TABLE ENDERECO_2(
    CEP INTEGER PRIMARY KEY,
    RUA VARCHAR(60),
    CIDADE VARCHAR(40)
);

--ALTERAMOS A TABELA ALUNO, ADICONAMOS UMA NOVA COLUNA
ALTER TABLE ALUNO
    ADD CPF VARCHAR(15) NOT NULL;
    
-- EXIBIR A ESTRUTURA DA TABELA

ALTER TABLE ALUNO
    ADD CONSTRAINT PK_ALUNO PRIMARY KEY (RA);
    
ALTER TABLE ALUNO
    ADD cep INTEGER;


ALTER TABLE ALUNO
    ADD CONSTRAINT FK_ALUNO_ENDERECO_2
    FOREIGN KEY(cep) REFERENCES 
    ENDERECO (cep);
    
--REMOVENDO UMA COLUNA NA TABELA
ALTER TABLE ALUNO
    DROP COLUMN CPF;
--MODIFICOU UMA COLUNA    
ALTER TABLE ALUNO
    MODIFY NOME CHAR(20);

ALTER TABLE ALUNO
    RENAME COLUMN NOME TO NOME_COMPLETO;    

RENAME ALUNO TO ESTUDANTE;
    
Drop Table Endereco Cascade Constraints;


DESC ESTUDANTE;


