DROP TABLE ALUNO;
DROP TABLE ENDERECO;

CREATE TABLE ENDERECO (
    CEP INT PRIMARY KEY,
    RUA VARCHAR(100),
    CIDADE VARCHAR(100),
    UF CHAR(2)
    );

CREATE TABLE ALUNO(
    RM INT,
    NOME VARCHAR(60) NOT NULL,
    DT_NASCIMENTO DATE,
    CEP INT REFERENCES ENDERECO(cep),
    CPF VARCHAR(14),
    CONSTRAINT uk_cpf UNIQUE (cpf),
    Constraint pk_rm PRIMARY KEY (rm)
    ); 