DROP TABLE CLIENTE;
DROP TABLE BICICLETA;
DROP TABLE GUIDÃO;
DROP TABLE SELIM;
DROP TABLE QUADRO;
DROP TABLE RODAS;

CREATE TABLE CLIENTE (
    ID_CLIENTE INT,
    RG VARCHAR(13),
    DT_NASCIMENTO DATE,
    E_MAIL VARCHAR(50),
    NR_TELEFONE VARCHAR(11),
    NM_NOME VARCHAR(60) NOT NULL,
    CEP INT REFERENCES ENDERECO(cep),
    CPF VARCHAR(14),
    COMPLEMENTO TEXT NOT NULL,
    CONSTRAINT pk_id_cliente PRIMARY KEY (ID_CLIENTE),
    CONSTRAINT uk_cpf UNIQUE (cpf)
    );

CREATE TABLE BICICLETA(
    MODELO_DA_BICICLETA,
    NOTA_FISCAL,
    CONSTRAINT pk_modelo_da_bicicleta PRIMARY KEY (MODELO_DA_BICIELTA)
    ); 

CREATE TABLE GUIDAO(
    MARCA_GUIDAO,
    MANOPLAS,
    MANETE_DE_FREIO
    ALAVANCA_DE_CAMBIO,
    CONSTRAINT pk_marca_guidao PRIMARY KEY (MARCA_GUIDAO)
    );

CREATE TABLE SELIM(
    MARCA_SELIM,
    CANOTE,
    MESA,
    ABRACADEIRA,
    CONSTRAINT pk_marca_selim PRIMARY KEY (MARCA_SELIM)
    ); 

CREATE TABLE QUADRO(
    MARCA_QUADRO,
    PEDAL,
    PEDIVELA,
    CAIXA_DE_DIRECAO,
    GARFO, 
    CONSTRAINT pk_marca_quadro PRIMARY KEY (MARCA_QUADRO)
    ); 

CREATE TABLE RODAS(
    MARCA_RODAS,
    FREIO,
    CAMBIO_TRASEIRO,
    CAMBIO_DIANTEIRO,
    CASSETE,
    CORRENTE,
    SUSPENSAO_TRASEIRA,
    CONSTRAINT pk_marca_rodas PRIMARY KEY (MARCA_RODAS)
    ); 
